#' @title Drawing Heatmap of CalculatePhysioMap()'s Output
#'
#' @description Draws a custom heatmap based on the result matrix generated by CalculatePhysioMap() function.
#'
#' @param PhysioResults Matrix of scores generated by CalculatePhysioMap().
#' @param ColorLevels An integer indicating how many colors to use when plotting the heatmap. Default is 100.
#' @param PDFFullName Full name (including the path) of the PDF file in which the heatmap is saved, e.g. "~/Desktop/outheat.pdf". For now
#' only exporting to a PDF is supported, so this parameter needs to be set or else the function breaks.
#' @param PDFWidth Width of the output PDF, in inches. Default is 7.
#' @param PDFHeight Height of the output PDF, in inches. Default is 7.
#' @param main The title of the heatmap. Default is an empty string (no title).
#'
#' @import grDevices graphics
#'
#' @return PhysioHeatmap returns(Invisibly) PDFFullName.
#'
#' @examples
#' randMatInpt <- matrix(data = rnorm(n = 4000,mean = 10,sd = 20),nrow = 400)
#' rownames(randMatInpt) <- paste("ROWS",1:400)
#' colnames(randMatInpt) <- paste("Sample",1:10)
#'
#' randMatRef <- matrix(data = rnorm(n = 12000,mean = 10,sd = 20),nrow = 400)
#' rownames(randMatRef) <- paste("ROWS",1:400)
#' colnames(randMatRef) <- paste("Space",1:30)
#'
#' res <- calculatePhysioMap(InputData = randMatInpt, Space = randMatRef)
#'
#' PhysioHeatmap(PhysioResults = res, PDFFullName = "~/Desktop/outheat.pdf", main = "Heatmap Testing")
#' @export PhysioHeatmap

#
PhysioHeatmap <- function(PhysioResults, ColorLevels = 100, PDFFullName, PDFWidth = 7, PDFHeight = 7, main = ""){
  PlotSize <- 50 #Make this user defined later (problem now is the labels! and colorkey!)
  #Check to see if PhysioResults is too big for PlotSize=50:
  if(max(dim(PhysioResults)) > PlotSize-10){
    warning("PhysioHeatmap is optimized for PhysioResults with less than 40 rows or columns")
  }
  PlotWidth <- (PDFWidth/max(PDFHeight,PDFWidth))*PlotSize
  #Check to see if it's gonna clip thru the heatmap(less likely):
  if(PlotWidth < ncol(PhysioResults)){
    warning("PDFWidth is too small, heatmap may not be plotted completely")
  }
  PlotHeight <- (PDFHeight/max(PDFHeight,PDFWidth))*PlotSize
  #Check to see if it's gonna clip thru the heatmap(more likely):
  if(PlotHeight < nrow(PhysioResults)){
    warning("PDFHeight is too small, heatmap may not be plotted completely")
  }

  PhysioResultsMorghed <- PhysioResults
  PhysioResultsMorghed <- round(ColorLevels*(PhysioResultsMorghed-min(PhysioResultsMorghed)) /
                                  (max(PhysioResultsMorghed)-min(PhysioResultsMorghed))) #wanted to have integers from 0 to 100
  COLORInterpolated <- colorRampPalette(colors = c(rgb(red = 0, green = 0, blue = 1),
                                                   rgb(red = 1, green = 1, blue = 0.8),
                                                   rgb(red = 1, green = 0, blue = 0)))(n = ColorLevels+1)
  pdf(PDFFullName, width = PDFWidth, height = PDFHeight)
  plot.new()
  plot.window(xlim = c(0,PlotWidth), ylim = c(0,PlotHeight)) #Number here limits the maximum number of boxes that can be drawn in each direction
  Xoffset <- (PlotWidth/2) - ncol(PhysioResults)/2
  Yoffset <- (PlotHeight/2) - nrow(PhysioResults)/2
  ColLabelYoffset <- Yoffset - (max(nchar(colnames(PhysioResultsMorghed)))-10)/7
  ColLabelXoffset <- Xoffset - max(nchar(colnames(PhysioResultsMorghed)))/9 + (1:ncol(PhysioResultsMorghed))
  RowLabelXoffset <- Xoffset + 1.5
  for(ROW in 1:nrow(PhysioResultsMorghed)){
    for(COL in 1:ncol(PhysioResultsMorghed)){
      rect(xleft = Xoffset+COL,xright = Xoffset+COL+1,ybottom = Yoffset+ROW,ytop = Yoffset+ROW+1,
           col = COLORInterpolated[PhysioResultsMorghed[ROW,COL]], border= "grey")
    }
  }
  text(labels = colnames(PhysioResultsMorghed), y = ColLabelYoffset, x = ColLabelXoffset, cex = 0.4, pos=1, srt=45, font = 2)
  text(labels = rownames(PhysioResultsMorghed), y = Yoffset+0.5+(1:nrow(PhysioResultsMorghed)), x = RowLabelXoffset, cex = 0.4, pos=2, font = 2)
  title(main = main)

  #Making the color key:
  rect(xleft = seq(Xoffset+ncol(PhysioResults),Xoffset+ncol(PhysioResults)+1.8,length.out = 10),
       xright = seq(Xoffset+ncol(PhysioResults)+0.2,Xoffset+ncol(PhysioResults)+2,length.out = 10),
       ybottom = rep(Yoffset+nrow(PhysioResults)+3,10), ytop = rep(Yoffset+nrow(PhysioResults)+4,10),
       col = colorRampPalette(colors = c(rgb(red = 0, green = 0, blue = 1),
                                         rgb(red = 1, green = 1, blue = 0.8),
                                         rgb(red = 1, green = 0, blue = 0)))(n = 10),
       border = NA)
  text(x = Xoffset+ncol(PhysioResults)+0.3, y = Yoffset+nrow(PhysioResults)+4, labels = round(min(PhysioResults)), pos = 3, cex = 0.4, srt=90)
  text(x = Xoffset+ncol(PhysioResults)+2.1, y = Yoffset+nrow(PhysioResults)+4, labels = round(max(PhysioResults)), pos = 3, cex = 0.4, srt=90)
  #

  dev.off()
  invisible(PDFFullName)
}
